# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'yys_k28tp_ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.L_cvImage = QtWidgets.QLabel(self.centralwidget)
        self.L_cvImage.setGeometry(QtCore.QRect(10, 10, 611, 541))
        self.L_cvImage.setText("")
        self.L_cvImage.setObjectName("L_cvImage")
        self.Btn_k28 = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_k28.setGeometry(QtCore.QRect(650, 20, 75, 23))
        self.Btn_k28.setObjectName("Btn_k28")
        self.Btn_tp = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_tp.setGeometry(QtCore.QRect(650, 60, 75, 23))
        self.Btn_tp.setObjectName("Btn_tp")
        self.Btn_k28tp = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_k28tp.setGeometry(QtCore.QRect(650, 100, 75, 23))
        self.Btn_k28tp.setObjectName("Btn_k28tp")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Btn_k28.setText(_translate("MainWindow", "k28"))
        self.Btn_tp.setText(_translate("MainWindow", "突破"))
        self.Btn_k28tp.setText(_translate("MainWindow", "k28+突破"))
